
services:
  mysql:
    image: mysql:latest
    container_name: mysql-server-2025
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app-network


volumes:
  redis-data:
  mysql-data:

networks:
  app-network:
    driver: bridge